name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: install mingw
      run: sudo apt install -y gcc-mingw-w64-x86-64-win32
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: exe
        path: '*.exe'
